import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider"
import Header from "@/components/Header";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata = {
  title: "MEDIMEET",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
        className={`${inter.className} `}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
             {/* header */}
             <Header />
        <main className="min-h-screen" >{children}</main>
        
        {/* footer */}
        <footer className="bg-muted/50 py-12">
         <div className="container mx-auto px-4 text-center text-gray-200">
           <p>HI this is footer</p>
          </div>
        </footer>
          </ThemeProvider>
      </body>
    </html>
  );
}
